### PR TITLE
fix: Integration functionality stop on terminal kill

### PR DESCRIPTION
**Pull request by ayush3160**
This pr fixes the behavior of recording when terminal is closed.

 
peek_1

After recording test cases in zsh shell 

peek_2

### CODE REVIEW

**Comment by khareyash05** [comment]
Great work! Works great with replay, please check on the record side

**Comment by khareyash05** [comment]
also add semicolons in your files, will cause havoc later if not present

**Comment by khareyash05** [comment]
Looks good! ALso check if Keploy and the application has been stopped or not, this will 100 percent ensure that the functionality is completed working

**Comment by khareyash05** [comment]
This is making, default running shell as bash, this isnt ideal,please look into the same

**Comment by shivamsouravjha** [comment]
if any terminal is open it is also closed please try to fix it

**Comment by khareyash05** [comment]
Well done @ayush3160

**Pull request merged**
