### PR TITLE
fix: Removed internal params from the default config string

### LINKED ISSUE #2168: [bug]: Remove internal config params while generating config in vscode extension
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Repo :- https://github.com/keploy/vscode-extension
While setting up the config through vscode-extension it adds internal params to keploy.yml file. For more reference see [#issue2076](https://github.com/keploy/keploy/issues/2076).

### Steps to reproduce

1. Start by setting up keploy config file.
2. Check keploy.yml file.

### Environment

None

### Version

Cloud

### Repository

keploy

### PR DESCRIPTION
**Pull request by ayush3160**
fixes : [#2168](https://github.com/keploy/keploy/issues/2168)

### Description

In this PR I have removed some internal params from the default config file string which is used to intialise the config.

### CODE REVIEW

**Comment by Sonichigo** [comment]
@ayush3160 can you resolve the conflicts

**Comment by ayush3160** [comment]
@Sonichigo , Is there any reason to commit `out` folder ? , I mean it is a build folder right.

**Comment by Sonichigo** [comment]
@ayush3160 no need to commit you can just resolve the conflicts via CLI. Since with the new release of the vscode extension version the old .`out` was deprecated. You can also resolve the conflict via web editior

**Comment by ayush3160** [comment]
@Sonichigo , I have resolved the conflicts please have a look.

**Review by Sonichigo — APPROVED** [review]
LGTM

**Pull request merged**
