### PR TITLE
Prototype Extension

### PR DESCRIPTION
**Pull request by SkySingh04**
This pull request serves as a prototype for vscode extension for Keploy. Further discussions about code/UI/UX/Testing and other improvements to the actual project can be done here.

Link to extension: https://marketplace.visualstudio.com/items?itemName=Akash-Singh04.heykeploy

Original Repository: https://github.com/Akash-Singh04/KeployVScodeExtension

### CODE REVIEW

**Comment by Sonichigo** [comment]
getting this error while recording

```
Error occurred Keploy Record: Error: ENOENT: no such file or directory, open '/home/sonichigi.linux/.vscode-server/extensions/akash-singh04.heykeploy-2.1.0/scripts/keploy_record_script.log'
```

Also i think it's better to use one-click installation for updating the keploy/download! Reason being, One-click can adjust based after detecting what the os and arch of the host machine is as well based on the command provide can be used for both native and docker in wsl and linux

**Comment by Sonichigo** [comment]
> getting this error while recording
> 
> ```
> Error occurred Keploy Record: Error: ENOENT: no such file or directory, open '/home/sonichigi.linux/.vscode-server/extensions/akash-singh04.heykeploy-2.1.0/scripts/keploy_record_script.log'
> ```
> 
> Also i think it's better to use one-click installation for updating the keploy/download! Reason being, One-click can adjust based after detecting what the os and arch of the host machine is as well based on the command provide can be used for both native and docker in wsl and linux

image

Also when trying to test-mode it doesn't allow me select the folder saying the path doesn't exist.

**Comment by Sarthak160** [comment]
Also When I tried to update keploy it throws an error on my debian12 lima env `/usr/local/bin/keploybin: 1: ELF: not found
/usr/local/bin/keploybin: 2: Syntax error: "(" unexpected (expecting ")")`

**Comment by Sarthak160** [comment]
And for docker in case of lima it's giving an error -
Screenshot 2024-03-07 at 3 01 27 PM

**Comment by SkySingh04** [comment]
> getting this error while recording
> 
> ```
> Error occurred Keploy Record: Error: ENOENT: no such file or directory, open '/home/sonichigi.linux/.vscode-server/extensions/akash-singh04.heykeploy-2.1.0/scripts/keploy_record_script.log'
> ```
> 
> Also i think it's better to use one-click installation for updating the keploy/download! Reason being, One-click can adjust based after detecting what the os and arch of the host machine is as well based on the command provide can be used for both native and docker in wsl and linux



Updated to now use one-click installation. The error you are getting is not supposed to be there as i had already patched it. Could you confirm if you are still facing this error on the latest version of the extension? I would recommend you use the extension from the microsoft store and let me know if you are still facing the error.

I tested it on both linux and windows and the ```keploy_record_script.log``` should automatically be generated the first time we are using the extension.

**Comment by SkySingh04** [comment]
> > getting this error while recording
> > ```
> > Error occurred Keploy Record: Error: ENOENT: no such file or directory, open '/home/sonichigi.linux/.vscode-server/extensions/akash-singh04.heykeploy-2.1.0/scripts/keploy_record_script.log'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also i think it's better to use one-click installation for updating the keploy/download! Reason being, One-click can adjust based after detecting what the os and arch of the host machine is as well based on the command provide can be used for both native and docker in wsl and linux
> 
> image
> Also when trying to test-mode it doesn't allow me select the folder saying the path doesn't exist.

When we click to choose the file path, it opens a separate dialogue box for us to choose the file
here is an attached video for reference:


https://github.com/keploy/vscode-extension/assets/114267538/d2798a34-e452-4a18-9ceb-112400bd1acb

**Comment by SkySingh04** [comment]
> Also When I tried to update keploy it throws an error on my debian12 lima env `/usr/local/bin/keploybin: 1: ELF: not found /usr/local/bin/keploybin: 2: Syntax error: "(" unexpected (expecting ")")`

Hey Sarthak, we are using /usr/local/bin/keploybin as the path to execute keploy in the ```exec``` command, as the alias is not available in the shell spawned by ```exec```.

The reason why we have to go through all of this is because of the depricted ```onDidWriteTerminalData```. I have further elaborated our approach and the limitation here:  [Limitation](https://github.com/Akash-Singh04/KeployVScodeExtension?tab=readme-ov-file#limitations)

 For the same reason to overcome the limitation in record and test command we make our own bash scripts to get the output from terminal.
 
 
 There is a solution to this, that we spawn a terminal session to run ```keploy --version``` and then kill it to get the version from another log output file. Let me know if the error is still therer, in which case we will have to implement that.
 
 
 #### Note: If we choose to decouple our terminal from vscode, we can then wrap it around a terminal event listener to get the outputs, just that it would be a separate session not in vscode.

**Comment by SkySingh04** [comment]
> And for docker in case of lima it's giving an error - Screenshot 2024-03-07 at 3 01 27 PM

Fixed this error by migrating it to the vscode terminal. Let me know if it works now

**Comment by Sonichigo** [comment]
> > > getting this error while recording
> > > ```
> > > Error occurred Keploy Record: Error: ENOENT: no such file or directory, open '/home/sonichigi.linux/.vscode-server/extensions/akash-singh04.heykeploy-2.1.0/scripts/keploy_record_script.log'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also i think it's better to use one-click installation for updating the keploy/download! Reason being, One-click can adjust based after detecting what the os and arch of the host machine is as well based on the command provide can be used for both native and docker in wsl and linux
> > 
> > 
> > image
> > Also when trying to test-mode it doesn't allow me select the folder saying the path doesn't exist.
> 
> When we click to choose the file path, it opens a separate dialogue box for us to choose the file here is an attached video for reference:
> 
>  Screencast.from.09-03-24.05_08_19.AM.IST.mp4

It works for me now! Earlier also i was using the keploy extension from vscode marketplace! Interestingly, I am seeing this

image

when selecting the project to capture the testcases.

**Comment by SkySingh04** [comment]
> It works for me now! Earlier also i was using the keploy extension from vscode marketplace! Interestingly, I am seeing this
> 
> image
> when selecting the project to capture the testcases.

I understand what is the issue here. We can refactor the logic to now select the folder containing the file, in this case would be ```gin-mongo``` and then cd into the folder in our script and then run our app command. It should work perfectly now. Please have a look at the attached video for reference.

https://github.com/keploy/vscode-extension/assets/114267538/a325c18e-b033-4de8-8729-975fcd9931a9

**Comment by SkySingh04** [comment]
@Sonichigo The new UI update is pushed. Do check it out and let me know how it looks! 

Currently all of the existing functionality of the prototype has been implemented whilst other buttons are currently disabled. If you want me to implement other features such as flags and generateConfig let me know!

**Comment by SkySingh04** [comment]
Update: Flags are now supported in the extension!

**Comment by Sonichigo** [comment]
The new UI looks great but the button size needs to be reduce both height and text a bit.
image

The padding btw the 3 section also needs to be a reduced. In both record and test screen this section can be shift above and placeholder for entering command and path can be kept below it. also manually entering maynot be required for the folder path
image
also, this needs to on top in small size since it is taking up most of space and people won't notice unless scrolling down. It's better to keep at top so they can once verify the command they have enter with the right project folder selected before running the command.
image

Extension Icon can be updated to maybe K or Keploy Logo! 
image


Ref: - https://stackoverflow.com/questions/42877083/set-icon-or-logo-for-extension-in-vscode

**Comment by SkySingh04** [comment]
Hey @Sonichigo I have made the requested UI Changes and [attached the videos here](https://github.com/orgs/keploy/discussions/1654#discussioncomment-8848006). Do let me know about further improvements!

**Comment by SkySingh04** [comment]
@Sonichigo Since GSoC has begun, I suppose we can close this prototype PR and use all of the discussions and knowledge gained here to continue onwards with the full development. Kindly Confirm

**Pull request closed without merging**
