### PR TITLE
HTML Rendering test

### PR DESCRIPTION
**Pull request by akshat99812**
This PR implements tests for our VS Code extension using the VS Code/test-cli and VS Code/test-electron modules. The following key features have been addressed:

Added a test suite inside extension.test.ts for registering a Test-Sidebar with our existing Sidebar Provider.
Tests the HTML content rendered in the Test-Sidebar to ensure correct rendering of webview elements (e.g., presence of a specific CSS link tag).

Tests for button clicks and webview component functionality (in progress).

Request for Assistance: I have successfully implemented tests for rendering HTML elements. However, I need some guidance in testing button clicks within the Svelte files. Could you provide assistance in writing and running tests for interactions with Svelte components?

### CODE REVIEW

**Comment by khareyash05** [comment]
@akshat99812 The pipelines are failing, please address the same

**Comment by akshat99812** [comment]
@khareyash05 , I have fixed the issue could you please review it

**Comment by khareyash05** [comment]
Could you please pass the DCO? if you click on details for the actions, you will get the steps as to how to do that. Also CCing @Hermione2408 for review as well

**Comment by khareyash05** [comment]
Also Could you please attach some screenshots for the same

**Comment by Hermione2408** [comment]
Hey @akshat99812 your PR has conflicts please resolve them

**Pull request closed without merging**
